<table>
	<caption>Visualisation des livres</caption>
	<thead>
		<tr>
			<th>ID</th>
			<th>TITRE</th>
			<th>SYNOPSIS</th>
			<th>ISBN</th>
			<th>AUTEUR</th>
			<th>GENRES</th>
			<th>PUBLICS</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td></td>
		</tr>
	</tbody>
</table>